# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c00e08920aa28fe02bd07d4af4437307b41bb97376a30fdbf5718e8aa5d8150221a2a275ca6dbed8ddc1c0ca285db81325feb95faa4af873b8a950d052a1dc0

test:
  secret_key_base: 2dbde5c501ab8f6037c938078729eb8ba4ea74a079300aab838305b94800474125b33f791049feee1d830f9139450242f3f613839fda546500f1903a40eb278f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
